dist: trusty
sudo: false

language: node_js
node_js:
  - "10.13.0"
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services: mongodb

cache: npm

jobs:
  include:
    # Test angular frontend
    - stage: test
      script: npm run client:test -- --single-run --no-progress --browser=ChromeHeadlessCI

    # Test node backend
    - stage: server-test
      before_script:
        - sleep 10
      script: npm run server:test
