dist: trusty
sudo: false

language: node_js
node_js:
  - "10.13.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: npm

jobs:
  include:
    # Test angular frontend
    - stage: client test
      script: npm run client:test -- --watch=false --progress=false --browsers=ChromeHeadlessCI

    # Test node backend
    - stage: server test
      service: mongodb
      before_script:
        - sleep 10
      script: npm run server:test
